server.port: 4403

spring:
  kafka:
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: txh.
      properties:
        enable.idempotence: true

    consumer:
      isolation-level: read_committed
    listener:
      type: batch

  datasource:
    url: jdbc:postgresql://localhost:56320/kafka
    username: kafka
    password: kafka
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app.storage.type: ${STORAGE_TYPE:local}

kafka.request.topic: student
kafka.reply.topic: result
kafka.group.id: student-result-group

s3:
  credentials:
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${S3_REGION:us-east-1}
  bucket: ${S3_BUCKET}
