version: '3.3'
services:

  fe:
    image: "it:tests-examples-fe.v1"

  dealer:
    image: "it:test-examples-dealer.v1"
    depends_on:
      - db
      - cache
    command: "--spring.profiles.active=compose"

  store:
    image: "it:test-examples-store.v1"
    command: "--spring.profiles.active=compose"

  db:
    image: mongo

  cache:
    image: redis

  nginx:
    image: nginx
    links:
      - fe
      - dealer
      - store
