version: '3.8'

services:

  zookeeper:
    image: zookeeper:3.6
    environment:
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:2.6.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    healthcheck:
      test: ['CMD', 'kafka-topics', '--bootstrap-server', '--version']
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: 'yes'
