version: '3.8'

x-zooServers: &zooServers server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

x-kafkaZookeeperConnect: &kafkaZookeeperConnect zoo1:2181,zoo2:2182,zoo3:2183
x-kafkaListenerSecProtocolMap: &kafkaListenerSecProtocolMap INTERNAL:PLAINTEXT,EXTERNAL_1:PLAINTEXT,PLAINTEXT:PLAINTEXT
x-kafkaLog4jLoggers: &kafkaLog4jLoggers kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
x-kafkaAllowPlainTextListener: &kafkaAllowPlainTextListener 'yes'

x-kafkaVariables: &kafkaVariables
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: *kafkaListenerSecProtocolMap
  KAFKA_CFG_ZOOKEEPER_CONNECT: *kafkaZookeeperConnect
  KAFKA_CFG_LOG4J_LOGGERS: *kafkaLog4jLoggers
  ALLOW_PLAINTEXT_LISTENER: *kafkaAllowPlainTextListener
  KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

services:
  zoo1:
    hostname: zoo1
    image: zookeeper:3.4.9
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: *zooServers
    volumes:
      - ./out/zk-and-kafka-bm/zoo1/data:/data
      - ./out/zk-and-kafka-bm/zoo1/datalog:/datalog

  zoo2:
    image: zookeeper:3.4.9
    hostname: zoo2
    ports:
      - "2182:2182"
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2182
      ZOO_SERVERS: *zooServers
    volumes:
      - ./out/zk-and-kafka-bm/zoo2/data:/data
      - ./out/zk-and-kafka-bm/zoo2/datalog:/datalog

  zoo3:
    image: zookeeper:3.4.9
    hostname: zoo3
    ports:
      - 2183:2183
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2183
      ZOO_SERVERS: *zooServers
    volumes:
      - ./out/zk-and-kafka-bm/zoo3/data:/data
      - ./out/zk-and-kafka-bm/zoo3/datalog:/datalog
  #
  broker1:
    image: bitnami/kafka:2.6.0
    hostname: broker1
    ports:
      - 9091:9091
    environment:
      KAFKA_CFG_LISTENERS: INTERNAL://broker1:19091,EXTERNAL_1://broker1:9091
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://broker1:19091,EXTERNAL_1://localhost:9091
      <<: *kafkaVariables
    volumes:
      - ./out/zk-and-kafka/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  broker2:
    image: bitnami/kafka:2.6.0
    hostname: broker2
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_LISTENERS: INTERNAL://broker2:19092,EXTERNAL_1://broker2:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://broker2:19092,EXTERNAL_1://localhost:9092
      <<: *kafkaVariables
    volumes:
      - ./out/zk-and-kafka/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  broker3:
    image: bitnami/kafka:2.6.0
    hostname: broker3
    ports:
      - 9093:9093
    environment:
      KAFKA_CFG_LISTENERS: INTERNAL://broker3:19093,EXTERNAL_1://broker3:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://broker3:19093,EXTERNAL_1://localhost:9093
      <<: *kafkaVariables
    volumes:
      - ./out/zk-and-kafka/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3
