version: '3.8'

services:
  spark-app:
    image: registry.gitlab.com/miamibeach87/test-examples/spark:0.0.3-SNAPSHOT
    container_name: spark-app
    ports:
      - 4201:4201
    environment:
      SPARK_APP_STORAGE_DIR: /app/data-sets
      CASSANDRA_URL: cassandra
      KAFKA_URL: kafka:29092
    volumes:
      - ~/data-sets:/app/data-sets
    depends_on:
      - cassandra
      - kafka

  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    build: service_dockerfile
    ports:
      - 9042:9042
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ../build/tmp/out/cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:3.11.2
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ${PWD}/cassandra_schema.cql:/schema.cql
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"

  zookeeper:
    image: zookeeper:3.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:2.6.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    healthcheck:
      test: ['CMD', 'kafka-topics', '--bootstrap-server', '--version']
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
