version: '3.3'

services:
  zoo1:
    hostname: zoo1
    image: &zooImage zookeeper:3.4.9
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./out/zk-and-kafka/zoo1/data:/data
      - ./out/zk-and-kafka/zoo1/datalog:/datalog

  zoo2:
    image: *zooImage
    hostname: zoo2
    ports:
      - 2182:2182
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2182
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./out/zk-and-kafka/zoo2/data:/data
      - ./out/zk-and-kafka/zoo2/datalog:/datalog

  zoo3:
    image: *zooImage
    hostname: zoo3
    ports:
      - 2183:2183
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2183
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./out/zk-and-kafka/zoo3/data:/data
      - ./out/zk-and-kafka/zoo3/datalog:/datalog

  broker1:
    image: &kafkaImage confluentinc/cp-kafka:5.5.1
    hostname: broker1
    ports:
      - 9091:9091
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker1:19091,EXTERNAL_1://localhost:9091
      <<: &kafkaVariables
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_1:PLAINTEXT
        KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
        KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - ./out/zk-and-kafka/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  broker2:
    image: *kafkaImage
    hostname: broker2
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker2:19092,EXTERNAL_1://localhost:9092
      <<: *kafkaVariables
    volumes:
      - ./out/zk-and-kafka/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  broker3:
    image: *kafkaImage
    hostname: broker3
    ports:
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker3:19093,EXTERNAL_1://localhost:9093
      <<: *kafkaVariables
    volumes:
      - ./out/zk-and-kafka/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zoo1
      - zoo2
      - zoo3
