server:
  port: 8201

spark:
  app.name: Spark Examples
  master: local[*]

  driver.memory: 32g
  worker.memory: 25g
  executor.memory: 25g
  rpc.message.maxSize: 1024
  stream.kafka.durations: 20

cassandra:
  host: 127.0.0.1
  username: cassandra
  password: cassandra

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: primary
    consumer:
      bootstrap-servers: localhost:9092
      group-id: teet
      auto-offset-reset: earliest
