server.port: 4305

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx.
    consumer:
      properties:
        isolation.level: read_committed
    listener:
      type: batch

app.storage.type: ${STORAGE_TYPE:local}

s3:
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  region: ${S3_REGION:us-east-1}
  bucket: ${S3_BUCKET}
  endpoint: https://${s3.region}.amazonaws.com
